# Generated by Django 5.2.4 on 2025-07-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        max_length=155,
                        null=True,
                        unique=True,
                        verbose_name="user_id",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=155, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Foydalanuvchilar",
                "verbose_name_plural": "Foydalanuvchilar",
                "db_table": "user",
            },
        ),
    ]
