# Generated by Django 5.2.4 on 2025-07-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeSMSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Telefon raqam"),
                ),
                ("message", models.TextField(verbose_name="Xabar matni")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Yuborilganmi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Erkin SMS yuborish",
                "verbose_name_plural": "Erkin SMSlar",
            },
        ),
        migrations.CreateModel(
            name="SendSMSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="SMS matni")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Yuborildi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.usermodel",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitta foydalanuvchiga SMS",
                "verbose_name_plural": "Bitta foydalanuvchiga SMSlar",
            },
        ),
    ]
