# Generated by Django 5.1.4 on 2025-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendSms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeSMSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Telefon raqam"),
                ),
                ("message", models.TextField(verbose_name="Xabar matni")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Yuborilganmi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Erkin SMS yuborish",
                "verbose_name_plural": "Erkin SMSlar",
            },
        ),
    ]
