# Generated by Django 5.2.4 on 2025-07-24 08:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, verbose_name="Footer matni"),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamasi",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="logo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayt logosi",
                "verbose_name_plural": "Sayt logosi",
            },
        ),
    ]
