# Generated by Django 5.1.4 on 2025-07-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_paymentsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsession",
            name="tracking_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="BTS tracking kodi"
            ),
        ),
    ]
